services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=$${POSTGRES_USER} PGDATABASE=$${POSTGRES_DB} PGHOST=localhost pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 5s
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.git:/app/.git
      - ./.pre-commit-config.yaml:/app/.pre-commit-config.yaml
      - backend_cache:/home/appuser/.cache
    command: >   
        sh -c "
        until pg_isready -h ${DATABASE_HOST} -U ${DATABASE_USER} -d ${DATABASE_NAME};
        do
          echo 'waiting for db';
          sleep 2;
        done;
        poetry run python manage.py migrate &&
        poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      PYTHONUNBUFFERED: 1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "
      pnpm install --frozen-lockfile &&
      pnpm run dev --host 0.0.0.0
      "
    environment:
      CI: "true"
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_cache:/home/appuser/.cache
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  backend_cache:
  frontend_cache: