[tool.poetry]
name = "library-management"
version = "0.1.0"
description = "Library management project"
authors = ["Ivan Grakov"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"
django = ">=5.0,<5.1"
djangorestframework = "^3.15.2"
django-filter = "^24.3"
psycopg2-binary = "^2.9.10"
drf-spectacular = "^0.27.2"
pillow = "^11.0.0"
mock = "^5.1.0"

[tool.poetry.group.dev.dependencies]
factory-boy = "^3.3.1"
ddt = "^1.7.2"
coverage = {extras = ["toml"], version = "^7.6.7"}
django-silk = "^5.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'
skip-string-normalization = true
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | htmlcov
    | k8s
    | frontend
    | docker
  )/
)
'''

[tool.coverage.run]
source = ['.']
omit = [
    '*/migrations/*',
    '*/tests/*',
    '*/management/*',
    '*/admin/*',
    '*/admin.py',
    '*/apps.py',
    '*/tests.py',
    '*/factories.py',
    'tasks.py',
    'manage.py',
    'asgi.py',
    'wsgi.py'
]

[tool.coverage.report]
fail_under = 90
exclude_lines = [
    'def __str__',
    'pragma: no cover',
    'raise AssertionError',
    'raise NotImplementedError',
]
skip_covered = true

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.12"
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "single"
