# Generated by Django 5.0 on 2024-10-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('two_letter_code', models.CharField(max_length=2)),
                ('three_letter_code', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
