# Generated by Django 5.0 on 2024-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_author_alter_book_language'),
        ('reference_values', '0002_alter_language_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='books', to='book.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='books', to='reference_values.language'),
        ),
    ]
