# Generated by Django 5.0 on 2024-11-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_author_alter_book_language'),
        ('reference_values', '0003_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='reference_values.genre'),
        ),
    ]
