# Generated by Django 5.0 on 2024-11-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_bookcopy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name': 'Book copy', 'verbose_name_plural': 'Book copies'},
        ),
    ]
