# Generated by Django 6.0.4 on 2026-04-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookcopy_options'),
        ('reader_card', '0003_alter_readercard_photo'),
        ('reference_values', '0004_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_values.hall'),
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='book.bookcopy')),
                ('reader_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='reader_card.readercard')),
            ],
            options={
                'verbose_name': 'Book loan',
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('book_copy',), name='unique_active_loan_per_copy')],
            },
        ),
    ]
