# Generated by Django 6.0.4 on 2026-05-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_bookcopy_hall_bookloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
