# Generated by Django 6.0.4 on 2026-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_author_last_name_alter_book_published_date_and_more'),
        ('reference_values', '0006_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='books', to='reference_values.author'),
        ),
    ]
