# Generated by Django 5.0 on 2024-08-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("published_date", models.DateField(null=True)),
                ("isbn", models.CharField(max_length=255, unique=True)),
                ("pages", models.IntegerField(null=True)),
                ("cover", models.URLField(null=True)),
                ("language", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Book",
            },
        ),
    ]
