# Generated by Django 5.0 on 2024-10-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_values', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateField(null=True)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('pages', models.IntegerField(null=True)),
                ('cover', models.URLField(null=True)),
                ('author', models.ManyToManyField(null=True, to='book.author')),
                ('language', models.ManyToManyField(null=True, to='reference_values.language')),
            ],
            options={
                'verbose_name': 'Book',
            },
        ),
    ]
