# Generated by Django 5.0 on 2024-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_name_author_last_name_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
