# Generated by Django 5.0 on 2024-10-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_pages_alter_book_published_date'),
        ('reference_values', '0002_alter_language_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='book.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(related_name='books', to='reference_values.language'),
        ),
    ]
