# Generated by Django 5.0 on 2024-10-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_values', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language'},
        ),
    ]
