# Generated by Django 5.0 on 2024-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader_card', '0001_initial'),
        ('reference_values', '0004_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='readercard',
            name='hall_access',
            field=models.ManyToManyField(blank=True, related_name='reader_cards', to='reference_values.hall'),
        ),
    ]
