# Generated by Django 6.0.4 on 2026-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader_card', '0002_readercard_hall_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readercard',
            name='photo',
            field=models.ImageField(blank=True, upload_to='reader_card_photos/'),
        ),
    ]
